# 添加机器人配置，dingding机器人的url和secret，根据prometheus的job名来分组发送告警
#地址后缀: 
#  /sendmsg   prometheus/alertmanager发送webhook地址
#  /yearning   yearning工单提醒转发到钉钉机器人群组（实现了多个群发送工单提醒需要配置文件配置钉钉的webhook地址）

dingtalk:
- job: "paixx"
  url: "https://oapi.dingtalk.com/robot/send?access_token=xxx"
  secret: "sss"
- job: "yinxx"
  url: "https://oapi.dingtalk.com/robot/send?access_token=xxx"
  secret: "xxx"


yearning:
- url: "https://oapi.dingtalk.com/robot/send?access_token=xx"
  secret: "xx"
- url: "https://oapi.dingtalk.com/robot/send?access_token=xxx"
  secret: "xxx"
  
