#地址后缀: 
#  /sendmsg   prometheus/alertmanager发送webhook地址
#  /yearning   yearning工单提醒转发到钉钉机器人群组（实现了多个群发送工单提醒需要配置文件配置钉钉的webhook地址）
# 

#isAtAll 为@全体，为true时 手机号就不生效

# 添加机器人配置，dingding机器人的url和secret，根据prometheus的job名来分组发送告警
#从alertmanager接收转发的请求地址
alertmanager:
  - job: "xxx"
    url: "https://oapi.dingtalk.com/robot/send?access_token=xxx"
    secret: "xxx"
    AtMobiles: ["132xxxxxxxx"]
    isAtAll: false
  - job: "xxx2"
    url: "https://oapi.dingtalk.com/robot/send?access_token=xxx"
    secret: "xxx"
    AtMobiles: ["155xxxxxxxx"]
    isAtAll: true


# 添加机器人配置，dingding机器人的url和secret .
#从yearning接收消息转发的地址
yearning:
  # sql审计
  - url: "https://oapi.dingtalk.com/robot/send?access_token=xxx"
    secret: "xxx"
    AtMobiles: ["155xxxxxxxx"]
    isAtAll: true
  #测试群
  - url: "https://oapi.dingtalk.com/robot/send?access_token=xxx"
    secret: "xxx"
    atMobiles: ["155xxxxxxxx","132xxxxxxxx"]
    isAtAll: false #是否at全体
  
