version: '3.1'
services:
  db:
    image: postgres
    container_name: db
    ports: 
      - 5432:5432
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
sonarqube:
  image: sonarqube:8.9.6-community
  container_name: sonarqube
  depends_on :
    - db
  ports:  
    - 9000:9000
  networks:
    - sonarnet
  environment:
    SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
    SGNAR_JDBC_USERNAME: sonar
    SONAR_JDBC_PASSWORD: sonar
networks:
  sonarnet:
    driver: bridge