apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dingtalk-autoscaler
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dingtalk
  minReplicas: 3  # 最小副本数
  maxReplicas: 10  # 最大副本数
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10  # 目标平均 CPU 利用率